<?php

return [
    'avatar_column' => 'avatar_url',
    'disk' => env('FILESYSTEM_DISK', 'public'),
    'visibility' => 'public', // or replace by filesystem disk visibility with fallback value

    'show_custom_fields' => true,
    'custom_fields' => [
        'nip' => [
            'type' => 'text',
            'label' => 'NIP',
            'placeholder' => 'Masukkan NIP',
            'id' => 'nip',
            'required' => false,
            'hint' => 'Nomor Induk Pegawai',
            'default' => '',
            'column_span' => 'full',
        ],
        'nomor_hp' => [
            'type' => 'text',
            'label' => 'Nomor HP',
            'placeholder' => 'Masukkan nomor HP',
            'id' => 'nomor-hp',
            'required' => true,
            'hint' => 'Gunakan format angka, 10-13 digit',
            'default' => '',
            'column_span' => 'full',
        ],
        'alamat' => [
            'type' => 'textarea',
            'label' => 'Alamat',
            'placeholder' => 'Masukkan alamat lengkap',
            'id' => 'alamat',
            'required' => true,
            'column_span' => 'full',
            'rows' => 3,
            'default' => '',
            'hint' => 'Alamat sesuai KTP atau domisili',
        ],
        'tempat_lahir' => [
            'type' => 'text',
            'label' => 'Tempat Lahir',
            'placeholder' => 'Masukkan tempat lahir',
            'id' => 'tempat-lahir',
            'required' => false,
            'default' => '',
            'column_span' => 'full',
        ],
        'tanggal_lahir' => [
            'type' => 'datetime',
            'label' => 'Tanggal Lahir',
            'placeholder' => 'Pilih tanggal lahir',
            'id' => 'tanggal-lahir',
            'required' => false,
            'format' => 'Y-m-d',
            'default' => '',
            'column_span' => 'full',
        ],
        'jenis_kelamin' => [
            'type' => 'select',
            'label' => 'Jenis Kelamin',
            'id' => 'jenis-kelamin',
            'required' => true,
            'options' => [
                'laki-laki' => 'Laki-laki',
                'perempuan' => 'Perempuan',
            ],
            'default' => '',
            'column_span' => 'full',
            'searchable' => true,
            'preload' => true,
            'native' => true,
        ],
        'agama' => [
            'type' => 'select',
            'label' => 'Agama',
            'id' => 'agama',
            'required' => false,
            'options' => [
                'islam' => 'Islam',
                'kristen' => 'Kristen',
                'katolik' => 'Katolik',
                'hindu' => 'Hindu',
                'buddha' => 'Buddha',
                'konghucu' => 'Konghucu',
                'lainnya' => 'Lainnya',
            ],
            'default' => '',
            'column_span' => 'full',
            'searchable' => true,
            'preload' => true,
        ],
        'status_pernikahan' => [
            'type' => 'select',
            'label' => 'Status Pernikahan',
            'id' => 'status-pernikahan',
            'required' => false,
            'options' => [
                'single' => 'Belum Menikah',
                'married' => 'Menikah',
                'divorced' => 'Cerai',
            ],
            'default' => '',
            'column_span' => 'full',
            'searchable' => true,
            'preload' => true,
        ],
        'jabatan' => [
            'type' => 'text',
            'label' => 'Jabatan',
            'placeholder' => 'Masukkan jabatan',
            'id' => 'jabatan',
            'required' => false,
            'default' => '',
            'column_span' => 'full',
        ],
        'departemen' => [
            'type' => 'text',
            'label' => 'Departemen',
            'placeholder' => 'Masukkan nama departemen',
            'id' => 'departemen',
            'required' => false,
            'default' => '',
            'column_span' => 'full',
        ],
        'pendidikan_terakhir' => [
            'type' => 'select',
            'label' => 'Pendidikan Terakhir',
            'id' => 'pendidikan-terakhir',
            'required' => false,
            'options' => [
                'sd' => 'SD',
                'smp' => 'SMP',
                'sma' => 'SMA/SMK',
                'd1' => 'D1',
                'd2' => 'D2',
                'd3' => 'D3',
                's1' => 'S1',
                's2' => 'S2',
                's3' => 'S3',
            ],
            'default' => '',
            'column_span' => 'full',
            'searchable' => true,
            'preload' => true,
        ],
    ],

];
